language: scala

scala:
  - 2.12.13
  - 2.13.4

jdk: openjdk11

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 14
  - nvm use 14
  - export NODE_PATH="$(npm config get prefix)"/lib/node_modules
  - npm install
  - npm install jsdom source-map-support

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

