language: scala

scala:
  - 2.11.8
  - 2.12.0

jdk:
- oraclejdk8

sudo: false
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

# Tricks to avoid unnecessary cache updates
script:
- sbt ++$TRAVIS_SCALA_VERSION test:compile
- find $HOME/.sbt -name "*.lock" -exec rm {} +
- find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} +
